### ISSUE TITLE
Add numbers to variable names

### ISSUE THREAD

**Issue by fragonrod8** [GuglioIsStupid/CBDQ-Python#3]
According to CBDQ, variables can have numbers too. 
Thus, regex expressions should be like:
     re.findall(r"#[a-zA-Z0-9]+#", tweet):

Thank you for your work!!! :)

**Comment by GuglioIsStupid** [comment]
Fixed in [d33925e33a6e98b12277f57c1653fda69f7abdd9](https://github.com/GuglioIsStupid/CBDQ-Python/commit/d33925e33a6e98b12277f57c1653fda69f7abdd9)

**Comment by fragonrod8** [comment]
Thank you for the quick improvement 💯
