### ISSUE TITLE
requirements.txt does not work with repls version of pip

### ISSUE THREAD

**Issue by SamBkamp** [GuglioIsStupid/CBDQ-Python#4]
running `pip install -r requirements.txt` on replit throws a bunch of `Could not find a version that satisfies the requirement <package name>`. I then tried to upgrade pip to a newer version, hoping it would recognize the correct lib versions. This then broke pip. It seems that according to the [replit forums](https://ask.replit.com/t/error-after-upgrading-pip/6543), installing libraries with pip is not the intended way of adding libraries, which is why pip breaks when it is updated. 

The work around I then used was to manually replace the version number of each library that would throw an error. This is probably a fine bandaid solution but as this project gets updated, it will more and more rely on features these older lib versions do not have. Plus it is incredibly annoying to do.

**Comment by GuglioIsStupid** [comment]
you don't exactly need to use requirements at all, its just 1 lib so i was thinking of removing it

**Comment by GuglioIsStupid** [comment]
Use the packages tab (found at the bottom left corner) to install tweepy (only extra lib used)
